// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Entity;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Repository.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("COD")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GetItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            COD = "Testowy",
                            Title = "pierwwszy post"
                        },
                        new
                        {
                            Id = 2,
                            COD = "Testowy12",
                            Title = "drugi post"
                        },
                        new
                        {
                            Id = 3,
                            COD = "Testowyas",
                            Title = "trzeci post"
                        },
                        new
                        {
                            Id = 4,
                            COD = "Testowyassa",
                            Title = "czwarty post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
